### ISSUE TITLE
Matching "aside" element; Saving space; More examples

### ISSUE THREAD

**Issue by peter-kehl** [igorlogius/persistent-element-remover#10]
Thank you for this.

1. Please add examples, like matching n-th child of some element...

2. I'm trying to hide the right "sidebar" on https://www.linkedin.com/feed and group feeds like https://www.linkedin.com/groups/4973032. Firefox dev tools show it as under "aside" element (never heard of it). Either way, the following doesn't match or do anything:
![image](https://github.com/igorlogius/persistent-element-remover/assets/4270240/eaecf5f4-3102-464e-bcb7-08f8ffd4131c)

3. In case this extension only hides the element, but it doesn't "shrink it": Could it have an option to shrink the space, please?
4. I guess if it actually removes the element from DOM, then it shrinks automatically. If it just changes the element's properties, I believe there is some CSS for it (display or visibility...?)?

Current Manjaro Linux x64, current Firefox 118.0.1. Extension 1.8.10 from https://addons.mozilla.org/en-US/firefox/addon/persistent-element-remover.

**Comment by igorlogius** [comment]
Hi, i'll try to give you some useful feedback.

1. i wont add any more examples, because there are already enough example on the web for CSS selectors. You can use anything that works with https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll and you can use the nth-child pseudo-class to access child elements ref. https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child

2. + 3. the addon does not hide anything. It removes all elements which match with the specified CSS selectors

4. yes, you are likely looking for an userstyle/script injection manager which allows you to modify the way the sidebar behaves. But this is a out of scope as a question. You could take a look at greasyfork or search for userscript for linkedIn and you might get lucky.
 
Hope these infos help.
